#!/bin/bash
command="$1"

if [ "$command" == "new" ]; then
    echo "Creating a new apache2 Virtual Host..."
    read -p "✏️  Project Name (lowercase, ex: test, my-project): " vhName
    read -p "📁  Project Root Path: " vhRoot
    read -p "🌐  Domain: " vhDomain
    read -p "🔐  Enable SSL (yes/no): " vhSSL
    vhConfTemplate="<VirtualHost *:80>
    ServerName $vhDomain
    ServerAlias www.$vhDomain
    ServerAdmin info@$vhDomain
    DocumentRoot $vhRoot

    <Directory $vhRoot>
            Options FollowSymLinks MultiViews
            Order Allow,Deny
            Allow from all
            AllowOverride All
            ReWriteEngine On
    </Directory>

    ErrorLog \${APACHE_LOG_DIR}/error.log
    CustomLog \${APACHE_LOG_DIR}/access.log combined
</VirtualHost>"
    echo $vhConfTemplate >"/etc/apache2/sites-available/$vhDomain.conf"

    eval "sudo a2ensite $vhName.conf"
    eval "sudo a2enmod rewrite"
    eval "sudo service apache2 restart"

    if [ vhSSL != "no" ]; then
        eval "sudo certbot --apache -d $vhDomain"
    fi
fi

if [ "$command" == "delete" ]; then
    echo "Deleting an apache2 Virtual Host..."
    read -p "🌐  Domain: " vhDomain
    eval "sudo a2dissite $vhDomain.conf"
    eval "sudo rm -rf /etc/apache2/sites-available/$vhDomain.conf"
    eval "sudo service apache2 restart"
fi
